---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-openshift
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-openshift
  template:
    metadata:
      labels:
        app: hello-openshift
    spec:
      containers:
      - name: hello-openshift
        image: registry.access.redhat.com/ubi8/ubi
        command: ['sh', '-c', 'echo The app is running! && sleep 3600000']

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-test
  template:
    metadata:
      labels:
        app: ping-test
      annotations:
    spec:
      containers:
      - name: pingtest
        image: quay.io/ykashtan/ubi8-ip:latest
        command: ["/bin/sh"]
        args: ["-c", "while true; do sleep 10000000;done"]
        securityContext:
          capabilities:
            add: ["NET_RAW", "NET_ADMIN"]

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: openshift-flask
    app.kubernetes.io/component: openshift-flask
    app.kubernetes.io/instance: openshift-flask
  name: openshift-flask
  namespace: test-helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: openshift-flask
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        deployment: openshift-flask
    spec:
      containers:
      - image: quay.io/cchenlp/helloworld:1.0
        imagePullPolicy: IfNotPresent
        name: openshift-flask
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30