apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-exec
spec:
  nodeName: "ip-10-0-174-27.us-east-2.compute.internal"
  containers:
  - name: liveness
    image: registry.access.redhat.com/ubi8/ubi
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 360000000
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5

---

apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-exec
spec:
  nodeName: "ip-10-0-174-27.us-east-2.compute.internal"
  containers:
  - name: liveness
    image: registry.access.redhat.com/ubi8/ubi
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 360000000
    livenessProbe:
      exec:
        command:
        - sleep
        - 31
      initialDelaySeconds: 5
      periodSeconds: 5