apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cchen-test
  labels:
    app: cchen-test
spec:
  selector:
    matchLabels:
      app: cchen-test
  template:
    metadata:
      labels:
        app: cchen-test
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: cluster.ocs.openshift.io/openshift-storage
                operator: In
                values:
                - ""
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
    spec:
      containers:
      - name: cchen-test
        image: registry.access.redhat.com/ubi7/ubi
        command: ['sh', '-c', 'echo The app is running! && sleep 3600']
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: FallbackToLogsOnError
      restartPolicy: Always
      terminationGracePeriodSeconds: 10