apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-cli
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim-1
spec:
  storageClassName: local-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi