apiVersion: v1
baseDomain: cchen.work
controlPlane:
  name: master
  platform: {}
  replicas: 3
compute:
- name: worker
  platform:
    openstack:
      type: ml.large
  replicas: 2
metadata:
  name: multi-osp
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.0.0/16
  serviceNetwork:
  - 172.30.0.0/16
  networkType: OVNKubernetes
platform:
  openstack:
    cloud: psi
    externalNetwork: provider_net_shared_3
    computeFlavor: m1.xlarge
    apiFloatingIP: 10.0.111.112
    ingressFloatingIP: 10.0.109.186
fips: false
pullSecret: '{"auths": ...}'
sshKey: ssh-ed25519 AAAA...