apiVersion: v1
kind: Pod
metadata:
  name: rhel7
  labels:
    app: rhel7
spec:
  containers:
  - name: myapp-container
    image: registry.access.redhat.com/ubi7/ubi
    command: ['sh', '-c', 'echo The app is running! && sleep 3600']
    volumeMounts:
    - name: local-disks
      mountPath: /data
  volumes:
    - name: local-disks
      persistentVolumeClaim:
        claimName: local-pvc-name

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/cinder
    volume.kubernetes.io/storage-provisioner: kubernetes.io/cinder
  name: local-pvc-name
  namespace: test-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard-csi
  volumeMode: Filesystem